#!/bin/bash
mv '"1986 Football",_collage' '"1986 Football Stuff_collage'
mv '"2001 Underdog Series",_collage' '"2001 The Underdog Series_collage'
mv '"2001 Langton Performance",_collage' '"2001 Langton Performances_collage'
mv '"2001 Studio 10 door",_collage' '"2001 Studio 10_collage'
mv '"2002 Milk, Self Portrait",_collage' '"2002 Milk, A Self Portrait_collage'
mv '"2001 Underdog Series",_collage' '"2002 Underdog_collage'
mv '"2001 No Bush",_collage' '"2001 No Bush Project_collage'
mv '"2002 Explorers",_collage' '"2002 The Explorers_collage'
mv '"2003 Topiary Sniper",_collage' '"2003 Topiary Surrender_collage'
mv '"2003 Estoy Enamoranda",_collage' '"2003 Estoy Enamamoranda_collage'
mv '"2004 EAGLE WARRIOR_ Shock and Awe",_collage' '"  Shock and Awe_collage'
mv '"2006 HermansHouseBook",_collage' '"2006 Hermans House First Edition Book_collage'
mv '"2007 Bacon Instead",_collage' '"2008 Bacon Instead_collage'
mv '"2006 Pizzeria Chinois",_collage' '"2008 Peripheral Cities_collage'
mv '"2009-2011 A=AGHT",_collage' '"2009 A=AGHT_collage'
mv '"2011 A=AGHT Travelguide Collage",_collage' '"2009 A=AGHT Travel Guide_collage'
mv '"2009-2011 A=AGHT",_collage' '"2010 A=AGHT Book_collage'
mv '"2011 Some People Like to Make Money, Some People Like to make Friends",_collage' '"2011 Some People Like to Make Money, Some People Like to Make Friends,_collage'
mv '"2006 HermansHouseBook",_collage' '"2013 Herman’s House, Second Edition_collage'
mv '"2006 HermansHouseBook",_collage' '"2013 Herman’s House_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2014 First Solitary Gardens Woodfox’s Cell_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2015 The Solitary Gardens Andry Street_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2016 The Solitary Gardens Andry Street_collage'
mv '"2017 Working MOdel Collage",_collage' '"2017 Working Model of the World_collage'
mv '"2018 Social Justice Seed Packets",_collage' '"2017 Social Justice Seed Packets_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2017 The Solitary Gardens Andry Street_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2018 The Solitary Gardens Andry Street_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2018 The Solitary Gardens Girls Club_collage'
mv '"2021 A Solitary Greenhouse MSU",_collage' '"2018 The Solitary Gardens Houston SHAPE_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2018 The Solitary Gardens North Carolina_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2018 The Solitary Gardens Philly_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2018 The Solitary Gardens Providence_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2018 The Solitary Gardens Xavier_collage'
mv '"2018 Round 48 (g)Row House (2018)",_collage' '"2018 Round 48 (g)Row House_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2019 The Solitary Gardens Andry Street_collage'
mv '"2019 Per(sister) (2019)",_collage' '"2019 Per(sister)_collage'
mv '"2021 Apothecafe",_collage' '"2019 Alien Apothecary_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2019 Abolitionist’s Apothecary_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2020 The Solitary Gardens Andry Street_collage'
mv '"2021 Growing Abolition MoMA",_collage' '"2020 Growing Abolition at MoMA PS1_collage'
mv '"2020 Barring Freedom",_collage' '"2020 Barring Freedom_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2020 The Abolitionist’s Apothecarts_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2020 Abolitionist’s Apothecary_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2021 The Solitary Gardens Andry Street_collage'
mv '"2021 Seeds of Resistence",_collage' '"2021 Seeds of Resistance_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2021 Abolitionist’s Apothecary_collage'
mv '"2021 A Solitary Greenhouse MSU",_collage' '"2021 Solitary Greenhouse MSU_collage'
mv '"2021 A Solitary Greenhouse MSU",_collage' '"2021 A Solitary Garden Florence Griswold_collage'
mv '"2021 A Solitary Greenhouse MSU",_collage' '"2021 A Solitary Garden Visible Records_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2021 The Abolitionist’s Sanctuary_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2022 Abolitionist’s Apothecary_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2022 The Abolitionist’s Sanctuary_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2022 Abolitionist Apothecarts_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2022 The Solitary Gardens Andry Street_collage'
mv '"2022 For Freedoms Billboard",_collage' '"2022 For Freedoms_collage'
mv '"2022 Freedom To Grow MoMA PS1 Installation (Nov)",_collage' '"2022 Freedom to Grow PS1 Installation (november)_collage'
mv '"2022-2024 Grow Plants Not Prisons Greenhouse",_collage' '"2022 Grow Plants Not Prisons Greenhouse_collage'
mv '"2022 Abolitionist's Fieldguide",_collage' '"2022 The Abolitionist’s Fieldguide_collage'
mv '"2021 A Solitary Greenhouse MSU",_collage' '"2022 A Solitary Greenhouse MoMA PS1 May_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2022 The Abolitionist’s Tea Party Tour (Creative Capital)_collage'
mv '"2022 Field Notes",_collage' '"2022 Fieldnotes_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2023 The Abolitionist’s Sanctuary_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2023 Abolitionist’s Apothecary_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2023 The Solitary Gardens Andry Street_collage'
mv '"2023 Garden of Good Grief 2023",_collage' '"2023 A Garden of Good Grief_collage'
mv '"2023-24 Studio Cajair",_collage' '"2023 Studio CAJAIR_collage'
mv '"2023 Free Soil PArty Counter Public",_collage' '"2023 Free Soil Party CounterPublic_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2024 The Abolitionist’s Sanctuary_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2024 Abolitionist’s Apothecary_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2024 The Solitary Gardens Andry Street_collage'
mv '"2019 A Solitary Garden UCSCIAS",_collage' '"2024 A Solitary Gardens St Charles_collage'
mv '"2024 Seeing Through Stone, San Jose",_collage' '"2024 Seeing Through Stone_collage'
mv '"2024 Behind These Walls Michener Museum",_collage' '"2024 Behind These Walls: Reckoning with Incarceration_collage'
mv '"2024 Color The Skies",_collage' '"2024 Color the Skies Fallen Prisons_collage'
mv '"2022 Abolitionist's Tea Party Tour",_collage' '"2024 The Abolitionist’s Tea Party_collage'
mv '"2024 The Locker Room",_collage' '"2024 The Locker Room_collage'
mv '"2025 Freedom To Grow",_collage' '"2025 Freedom to Grow Community Archive_collage'
mv '"2025 Freedom To Grow",_collage' '"2025 Freedom to Grow_collage'
